@include('home.header')



<!-- Banner/Slider -->
<div class="page-head section row-vm light">
	<div class="imagebg">
		<img src="images/header-bg-b.jpg" alt="page-head">
	</div>
	<div class="container">
		<div class="row text-center">
			<div class="col-md-12">
				<h2>Terms & Conditions</h2>
				<div class="page-breadcrumb">
					<ul class="breadcrumb">
						<li><a href="home">Home</a></li>
						<li class="active"><span>Terms & Conditions</span></li>
					</ul>
				</div>
			</div>
		</div>
	</div>
</div>
<!-- #end Banner/Slider -->
</header>




<!-- Section -->
<div class="section section-pad">
	<div class="container">
		<div class="row">
			<div class="col-md-12 res-m-bttm">

				<div class="post post-single">
					<h1>Terms And Conditions</h1>

					<div class="post-meta">
						<b class="Author-left">You are responsible for reading and understanding these Terms and Conditions pursuant to which all tournaments, gain of skill, trades, transactions, or offerings via this site are governed.</b>
					</div><br>
					<div class="post-entry">
						<p>
							1. The trade name is owned and operated under regulated authority.<br>
							2. The Company does not provide a market or exchange amongst or between customers for trades, securities, derivatives, options, or market speculations. Each trade placed by a customer is an individual skill-based game between the customer and the Company and is not a trade, security, derivative, option, or market speculation, nor is it transferable, negotiable or assignable to or with any third party. Actual exchange traded binary options also exist and are fundamentally different to the offerings available to customers via this site. On an actual options exchange participants trade against other participants over the exchange. This site is not an options nor futures exchange which are regulated differently, by regulators who oversee dealings and dealers in tradable financial instruments, financial markets, options and/or futures as well as the exchanges over which such financial products are dealt. <br>
							3. Prices of a stock, commodity, currency or index can be highly volatile and difficult to predict. Due to such volatility, no trade placed within this site should be considered a safe bet. The services offered by this site are only suitable for customers who understand the risks involved and are able to bear the loss of all the money they stake. The maximum losses that may be incurred by any customer is limited to the amount of money paid by the customer to the Company. <br>
							4. Each customer will create a personal password which should be kept strictly confidential as all transactions where a customer’s email and password have been correctly entered will be regarded as valid, subject to meeting the criteria for placing trades laid down in these Terms and Conditions. You agree to be fully and personally liable for the due settlement of every transaction entered under your account. The Company will not be liable for any loss you may incur as a result of misuse of your account and accepts no liability resulting from any unauthorized use, whether fraudulent or otherwise. This includes, without limitation, any transactions by members of your family or entourage who have gained access to your account. You are responsible for ensuring that you alone control access to the account, and that no minors are granted access to trading on this site. You remain fully liable for all trades and credit/debit card transactions entered for your account. You agree to indemnify the Company in respect to all costs and losses of any kind whatsoever as may be incurred by the Company as a result, direct or indirect, of your failure to perform or settle such transactions.<br>
							5. The Company will not be liable in any way to any customer in the event of force majeure, or for the act of any Government or legal authority, or for the failure of or damage or destruction to its computer systems, data or records or any part thereof, or for delays, losses, errors or omissions resulting from the failure or mismanagement of any telecommunications or computer equipment or software. The Company reserves the right to void any part or all of any trade or any event that is not completed (e.g. frozen, abandoned, and postponed). The Company may, at its sole discretion, suspend the relevant offerings on our site and cancel all trades relevant to any assets where: • the stock exchange or interbank authority suspends trading activities of any asset offered on this site, • a blatant error is made in transmission of any asset data, • the Company has reason to believe that a trade is placed after the outcome of an event is known or with reasonably foreseeable knowledge of the event which gives an undue advantage or superior position; • as a result of political, economic, military or monetary events (including unusual market volatility or liquidity) or any circumstances outside the control, responsibility or power of the Company, the continued operation of any offering on this site is not reasonably practicable without adversely affecting and prejudicing the interests of customers or the Company; or • there is a breakdown in the means of communication normally employed in determining the price or value of any of the assets or where the price or value of any of the assets cannot be promptly or accurately ascertained. In such event, the Company shall refund the stakes corresponding to any cancelled trades to the customer, and no further claim may be entertained against the Company in connection thereto. <br>
							6. The Company reserves the right at its sole discretion to refuse and/or cancel services to anyone for any reason including, without limitation, any instance where: • the customer’s activities at this site may be illegal in that person’s country or state; • the Company may be contacted by legal authorities or regulators from that person’s country or state; • the Company may suffer any pecuniary, fiscal or regulatory disadvantage by virtue of that person’s activities at this site; or • transactions on this site are performed in breach of the Terms and Conditions. <br>
							7. No person shall abuse this site for the purpose of money laundering. The Company employs best-practice anti-money laundering procedures, which can have several effects on customers. The Company reserves the right to refuse to do business with, to discontinue to do business with, and to reverse the transactions of, customers who do not accept or adhere to these anti-money laundering processes. Accounts may be frozen or closed if satisfactory customer due diligence documentation is not provided. The anti-money laundering processes have the following effects on customers: • You must fill into the account opening form all requested details that establish your identity. • The Company may, from time to time, at its sole discretion, require you to provide proof of identity (such as notarized copy of passport or other means of identity verification as the Company deems required under the circumstances) and may suspend an account until such proof has been provided to its satisfaction. • You agree that we may use the personal information you provide in order to conduct anti-fraud checks. Personal information that you provide may be disclosed to a credit reference or fraud prevention agency, which may keep a record of that information. • Earnings payouts or withdrawals may only be paid to the initiator of an account. When a customer maintains an account by means of telegraphic deposits, earnings payouts or withdrawals are only paid to the holder of the originating bank account, and the onus is on the customer to ensure that account number and name accompany all transfers to the Company. When a customer maintains an account by means of credit/debit card deposits, earnings payouts or withdrawals are only paid back to the same card. • Only one account is allowed per person. No earnings payouts may be collected on accounts opened in false names or on multiple accounts opened by the same person. <br>
							8. The Company may impose trade volume and other limits on Customer accounts at its sole discretion. The current trade volume limit upon account opening is USD/GBP/EUR 25,000/day maximum trading volume. The maximum account size (i.e. cash balance) is USD/GBP/EUR 30,000. The maximum outstanding payout with respect to active trades at a given time per account is USD/GBP/EUR 30,000. The maximum payout to any one customer with respect to any one day’s completed trades is USD/GBP/EUR 30,000. These limits are increased once a customer fully authenticates himself; where after the new maximum trading volume will be USD/GBP/EUR 250,000/day, having a maximum account size of USD/GBP/EUR 250,000, and a maximum outstanding payout for active trades at a given time per account of USD/GBP/EUR 250,000. Payouts for completed trades remain subject to the stated daily maximum payout to any one customer in any one day, irrespective of total trades’ stakes or number of winning trades. The onus is on the customer to stay within the stated limits. Once a customer’s account balance exceeds the maximum account size, then withdrawals must be made to bring the balance to within the limits. <br>
							9. Persons with insider knowledge of any financial market or instrument are prohibited from trading at this site. It is a condition of the Company’s acceptance of trades from you, and by your offering to place trades that you represent that: (a) you are not prohibited from placing the trade by any term of your contract of employment or any rule of a Financial Market Governing Body which applies to you; (b) you are not aware of any circumstances which would make the placing of the trade a breach of a rule applied by a Financial Market Governing Body; (c) when a trade is placed on the outcome of any event or process (“the event”) you do not possess advanced superior knowledge as to the outcome of the event or on the likelihood of anything occurring or not occurring; (d) you are the person whose details are provided in connection with your registration; and (e) you are not an undischarged bankrupt or in a voluntary arrangement with your creditors. In the event of any such representation by you proving to be false, your trade stakes will be forfeit and the Company shall not be obliged to make any payouts which might otherwise have been payable. <br>
							10. Asset pricing: All prices displayed on this site are based on official quotes from the relevant stock exchange or interbank authorities. The Company provides its customers with real-time streaming prices or quotes by collecting and aggregating information sourced through independent price providers, relevant exchanges, and interbank authorities who supply liquidity and information to the global financial, forex and/or futures markets. The current market price we display represents our objective view of the prices available to arm’s length traders at the relevant time. In order to ascertain and calculate current fair market prices the Company accesses a number of different data sources and is required to take a number of factors into account including volume weighting and market volatility. All trades are priced and settled using the current market price as displayed by the Company at the relevant time. The company’s pricing on all available assets is fully transparent and the complete price history for all assets is made available to all customers using the Tick by Tick Search function. <br>
							11. Strategy: The stakes for each trade are subtracted from the customer’s account at the time the customer places the trade. The earnings for each winning trade are credited to the customer’s account following the trade’s expiry. The strike price given for each trade is according to the official price quote indicated by the Company (“the Offered Price”) and is recorded according to the Offered Price as exists at the time the trade is recorded on our Transactions Server. The expiry price given for each trade is according to the official price quote indicated by the Company at the time of the trade expiry. For assets which have both an ask and bid price quote, the mean price is used and is determined by (Ask+Bid)/2 = Mean Price. <br>
							12. Profit calculation: We offer up to 90% profit on successful trades. Variable profit rates apply. Profit rates are in flux and can change rapidly. The available profit ranges from 70% to 90%. At the highest rate 90%, this is a 190% total return on your trade inclusive of the trade stakes returned plus the profit rate. The governing profit rate on a trade is the rate shown at the time the trade is recorded on our Transactions Server. <br>
							13. Expiry lockout: Trading is unavailable within the relevant lockout period prior to expiry. The lockout period for each expiry is indicated by the clock on the chart when the expiry is selected. Once the lockout time for a given expiry is reached, a trade recorded after this time will be registered for the next expiry of that kind. Any trade which is filled by our Transaction Server following the lockout period will automatically carry over and be filled for the following expiry of that kind. Placing a trade very close to the lockout will run the risk of the trade being filled for the following expiry. We also offer Countdown expiries of 60 seconds, 120 seconds and 300 seconds with no lockout. <br>
							14. Each trade successfully placed by the customer will be given an individual transaction confirmation number. Once a trade is placed, it cannot be cancelled. Trades will only be valid, subject to meeting the criteria for placing trades laid down in these Terms and Conditions, if accepted by our Transactions Server. The Company is not liable for the settlement of any trade where a transaction confirmation number is not issued and displayed in the customer’s ‘Account Journal’ page of this site. <br>
							15. Our Transactions Server log governs with respect to all determinations of timing including the time at which a trade is placed, the applicable profit rate, strike price, and expiry price, irrespective of the time at which the customer may have attempted to place the trade or the time at which the stock exchange or interbank authorities published prices. In the event of a query, it is your responsibility to be notified at the earliest opportunity. Any queries relating to a trade must be raised no later than twelve hours after the trade has been settled. The Company cannot guarantee that it will be able to respond to any query which is not raised within this time. Our real-time streaming price data governs with respect to any issues involving the pricing or settlement of trades irrespective of any differing price information which might be displayed by third party data providers. With respect to any issues as to times, prices, and trade settlements, the decision of the Company shall be final and binding. <br>
							16. The Company reserves the right to correct any obvious errors and to void any trades placed where such have occurred. In the event that any trade’s pricing grossly deviates from fair market prices due to an undetected programming error, bug or glitch in our software, the Company reserves the right to cancel or reverse such transactions upon notification to the customer of the nature of the computer error that led to the mis-pricing. In such event, the Company shall refund to the customer the stakes corresponding to any cancelled trades, and no further claim may be entertained against the Company in connection thereto. Customers have a duty to report to the Company any problems or suspected system inadequacies that they may experience including without limitation extrinsic information providing asset data ahead of the Company’s and customers may not abuse system problems or inadequacies for profit. The Company will endeavor to resolve any such difficulties in the shortest time possible. <br>
							17. Any concern or claim over a trade should first be e-mailed to us at our support mail and we will make every effort to resolve the matter in a mutually satisfactory manner. However, if you still feel that you have been unfairly treated your dispute should be raised. Any information given on the this site, and/or emails or newsletters sent by the Company related thereto is not intended as financial or trade advice and the Company will not accept any liability for either its comprehensiveness or accuracy. Customers agree to receive such information from the Company and its partners unless they ask to be opted out from the receipt of any such mailings. <br>
							18. With respect to any asset pricing, data or other information displayed on this site, (a) such content is indicative only and neither the Company nor any of its licensors gives any warranty that the supply of content on this site will be uninterrupted or as to its accuracy; (b) the Company and its licensors are not responsible or liable if any such content is inaccurate or incomplete; (c) the Company and its licensors are not responsible or liable for any actions that you take or do not take based on such content; (d) such content is proprietary to the Company and/or its licensors and you are not permitted to retransmit, redistribute, publish, disclose or display in whole or in part such content to others; and (e) all content is provided for your own personal usage and the distribution, reproduction or commercial exploitation of such content in any manner whatsoever is prohibited. <br>
							19. The Company may at any time, at its sole discretion, alter or amend, add, withdraw, or suspend from the site any of the available tournaments, games of skill, trading services or offerings, or any part thereof and may alter stakes, features, specifications, capabilities, functions and/or other characteristics of any of the available tournaments, games of skill, trading services or offerings, or any part thereof; and may alter or change the rules and scope of this service from time to time, including changes to these Terms and Conditions. Any change made shall not apply retrospectively and shall only apply to the available tournaments, games of skill, trading services or offerings after such change. <br>
							20. In the event that any provision of these Terms and Conditions is deemed by any competent authority to be unenforceable or invalid, the relevant provision shall be modified to allow it to be enforced in line with the intention of the original text to the fullest extent permitted by applicable law. The validity and enforceability of the remaining provisions of these Terms and Conditions shall not be affected. Any provision of these Terms and Conditions which may be deemed invalid, illegal or unenforceable in any jurisdiction will be ineffective in that particular jurisdiction, without affecting the validity, legality or enforceability of that provision in other jurisdictions. In the event of any differences between the English version and any other language, the English version shall prevail. <br>
							21. The company may charge you for a 25% trade commission depends on the signal software used in your account to facilitate high profit realization <br>
							22. All successful deposits are received instantly into our account. You will not be entitled to interest on funds that are held in your account. Your account should not be used as a mere depository for funds or as a substitute for a bank. Customer accounts which have zero funds in them and are not used for a period of 12 consecutive months shall be closed. In the event that you have funds in your account and you do not play any game or place any trade on the site for a period of 36 consecutive months, the Company will advise you in writing; and, thereafter, the Company may charge a monthly management fee of USD/GBP/EUR 30 until the account is used for trading or the funds are withdrawn. <br>
							23. Only one account is allowed per customer. The Company reserves the right to close any duplicate accounts. In respect of any such duplicate accounts that are located, the Company reserves the right to cancel any transactions on the duplicate account. The Company also reserves the right to suspend or close any account and cancel any associated transactions where the account holder and the owner of the funding instrument are not the same. Employees of the Company may not open an account or register on this site whether in their own name or on behalf of another. <br>
							24. You may choose to contact us to close your account held with the Company. Your account may be closed if you do not have any open trade positions and if you have complied with the requested “Know Your Client” procedures to enable you to withdraw any pending funds in your account. The Company may, at its sole discretion, exclude selected players from receiving the selected promotions such as bonuses, free plays/trades, money-back specials, and/or any other promotions and offers introduced by the Company from time to time. <br>
							25. Notices and other communications delivered or mailed to the postal address or to the electronic-mail address provided by you shall, until we have received notice in writing of any different address, be deemed to have been personally delivered and received once sent, whether actually received or not. <br>
							26. You may only open an account at this site on condition that:<br>
						</p>
						<blockquote>• you have read these Legal Terms and Conditions in full and understood that all actions you take on this site are subject to these Terms and Conditions; <br>
							• you have read our privacy statement and hereby give us consent to process your personal information as outlined therein; <br>
							• you are over 18 years of age, unless you are an Estonian resident whereby you would have to be over 21; <br>
							• you have sufficient experience and knowledge in matters of financial markets to be capable of evaluating the merits and risks of the tournaments, games of skill, and/or trading available via this site and have done so without relying on any information contained at this site. <br>
						</blockquote>
					</div>
				</div>

			</div>
		</div>
	</div>
</div>
<!-- End Section -->



<!-- Section -->
<div class="section section-pad-md bg-grey">
 <div class="container">
	 <div class="content row">
		 <div class="owl-carousel has-carousel no-dots" data-items="6" data-loop="true" data-dots="false" data-auto="false">
			 <div class="logo-item"><img alt="" width="190" height="82" src="images/logo/1.png"></div>
			 <div class="logo-item"><img alt="" width="190" height="82" src="images/logo/2.png"></div>
			 <div class="logo-item"><img alt="" width="190" height="82" src="images/logo/3.png"></div>
			 <div class="logo-item"><img alt="" width="190" height="82" src="images/logo/4.png"></div>
			 <div class="logo-item"><img alt="" width="190" height="82" src="images/logo/5.png"></div>
			 <div class="logo-item"><img alt="" width="190" height="82" src="images/logo/6.png"></div>
		 </div>

	 </div>
 </div>
</div>
<!-- End Section -->



@include('home.footer')